# Production environment
environment: "production"

# Log only warning messages or higher
logger: "console"
log: "warning"
log_format: "%d %m"

# Disable the display of error messages and stack traces on the frontend
show_errors: 0
show_stacktrace: 0

# disable server tokens in production environments
no_server_tokens: 1
